spring:
  application:
    name: garage
  datasource:
    url: jdbc:postgresql://localhost:5432/Garagedb
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true